/*
 * vu0_micro.c — VU0 Micro Program Library for GTE Acceleration
 *
 * VU0 micro programs assembled from .vsm sources via dvp-as.
 * Binary data generated by cmake build pipeline (dvp-as → extract → bin2c).
 * Uploaded to VU0 micro memory at init.
 * Data exchange via VU0 data memory (0x11004000).
 */
#include "vu0_micro.h"

#ifdef _EE

#include <string.h>

/* Generated headers from cmake VU0 assembly pipeline.
 * Each provides: unsigned char <name>_data[] and unsigned int size_<name>_data */
#include "mvmva_full_data.h"
#include "mvmva_core_data.h"

/* ====================================================================
 * Initialization
 * ==================================================================== */

void vu0_micro_init(void)
{
    volatile uint8_t *micro_mem = (volatile uint8_t *)VU0_MICRO_MEM;

    /* Copy mvmva_full at offset 0x000 */
    memcpy((void *)micro_mem, mvmva_full_data, size_mvmva_full_data);

    /* Copy mvmva_core at offset 0x088 */
    memcpy((void *)(micro_mem + VU0_PROG_MVMVA_CORE), mvmva_core_data,
           size_mvmva_core_data);

    /* Sync: ensure all writes are visible to VU0 */
    __asm__ __volatile__("sync.l" ::: "memory");
}

/* ====================================================================
 * Matrix Refresh — write matrix to VU0 data memory
 *
 * Takes the same mx_cv encoding as vu0_prepare_mvmva().
 * Writes 4 QWs (col1, col2, col3, translation) to VU0 data memory
 * at the appropriate QW offset for the requested matrix.
 * ==================================================================== */

/* Forward declarations from gte.c (VU0 float matrix caches) */
extern float vu0_rt_col1[4], vu0_rt_col2[4], vu0_rt_col3[4], vu0_rt_trans[4];
extern float vu0_lt_col1[4], vu0_lt_col2[4], vu0_lt_col3[4];
extern float vu0_lc_col1[4], vu0_lc_col2[4], vu0_lc_col3[4];
extern float vu0_bk_trans[4], vu0_zero_trans[4];

/* Dirty check functions from gte.c */
extern int vu0_rt_is_dirty(R3000CPU *cpu);
extern int vu0_lt_is_dirty(R3000CPU *cpu);
extern int vu0_lc_is_dirty(R3000CPU *cpu);
extern int vu0_bk_is_dirty(R3000CPU *cpu);
extern void vu0_refresh_rt_matrix(R3000CPU *cpu);
extern void vu0_refresh_lt_matrix(R3000CPU *cpu);
extern void vu0_refresh_lc_matrix(R3000CPU *cpu);
extern void vu0_refresh_bk_trans(R3000CPU *cpu);

/* Write a 4-QW matrix block (col1,col2,col3,trans) to VU0 data memory.
 * Uses uncached store (VU data mem is in I/O region). */
static void vu0_write_matrix_to_datamem(int qw_base,
                                         const float *col1, const float *col2,
                                         const float *col3, const float *trans)
{
    /* VU0 data mem is at 0x11000000, accessible via normal stores.
     * On PS2 hardware this address range is uncached, so stores are
     * immediately visible to VU0. */
    volatile float *dst = (volatile float *)(VU0_DATA_MEM + qw_base * 16);

    /* QW[base+0] = col1 */
    dst[0] = col1[0]; dst[1] = col1[1]; dst[2] = col1[2]; dst[3] = col1[3];
    /* QW[base+1] = col2 */
    dst[4] = col2[0]; dst[5] = col2[1]; dst[6] = col2[2]; dst[7] = col2[3];
    /* QW[base+2] = col3 */
    dst[8] = col3[0]; dst[9] = col3[1]; dst[10] = col3[2]; dst[11] = col3[3];
    /* QW[base+3] = translation */
    dst[12] = trans[0]; dst[13] = trans[1]; dst[14] = trans[2]; dst[15] = trans[3];
}

void vu0_micro_prepare_matrix(R3000CPU *cpu, uint32_t mx_cv)
{
    int mx = mx_cv & 3;
    int cv = mx_cv >> 2;

    /* Always write to QW[1-4] — micro program _FULL reads from fixed QW[1-4].
     * The separate QW bases (RT=1, LT=5, LC=9) are reserved for future
     * multi-matrix programs that preload several matrices simultaneously. */
    float *col1, *col2, *col3;

    switch (mx) {
    case 0:
        if (vu0_rt_is_dirty(cpu)) vu0_refresh_rt_matrix(cpu);
        col1 = vu0_rt_col1; col2 = vu0_rt_col2; col3 = vu0_rt_col3;
        break;
    case 1:
        if (vu0_lt_is_dirty(cpu)) vu0_refresh_lt_matrix(cpu);
        col1 = vu0_lt_col1; col2 = vu0_lt_col2; col3 = vu0_lt_col3;
        break;
    default:
        if (vu0_lc_is_dirty(cpu)) vu0_refresh_lc_matrix(cpu);
        col1 = vu0_lc_col1; col2 = vu0_lc_col2; col3 = vu0_lc_col3;
        break;
    }

    /* Determine translation vector */
    float *trans;
    switch (cv) {
    case 0:
        if (mx != 0 && vu0_rt_is_dirty(cpu)) vu0_refresh_rt_matrix(cpu);
        trans = vu0_rt_trans;
        break;
    case 1:
        if (vu0_bk_is_dirty(cpu)) vu0_refresh_bk_trans(cpu);
        trans = vu0_bk_trans;
        break;
    default:
        trans = vu0_zero_trans;
        break;
    }

    vu0_write_matrix_to_datamem(VU0_QW_RT_COL1, col1, col2, col3, trans);
}

#endif /* _EE */
